defaults:
  - model: resnet18
  - opt: adam
  - loss: cross_entropy
  - dataset: GTSRB
  - train: default
  - wandb: default
  - experiments: experiment_1_1
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null