project_name: "DLA-Lab2"
run_name: "Experiment_1"

model:
  checkpoint:   "distilbert/distilbert-base-uncased" #"openai/clip-vit-base-patch32"
  task: "feature-extraction"

opt:
  lr: 1e-5

exercise_1:
  read_data: True
  build_classifier: True

exercise_3:
  k: 10
  ret_path: DLA-Lab2/retrieval_results/

dataset:
  name:   "cornell-movie-review-data/rotten_tomatoes" #"jxie/flickr8k"
  ft_path: "DLA-Lab2/features/image_ft.pt"

training:
  batch_size: 64
  epochs: 10